In [2]:
import os
import pandas as pd
import numpy as np
from os.path import *

## Load data
- load csv and convert to numpy

In [78]:
%load_ext autoreload
%autoreload 2
from converter import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [79]:
label = pd.read_csv('1_label.csv')
neuro = pd.read_csv('1_neuro.csv')

In [80]:
#with out timestamp

start = 1548120820000
end = 1548121672000
cols = ['delta', 'lowAlpha', 'highAlpha', 'lowBeta', 'highBeta', 'lowGamma', 'middleGamma', 'theta']
data = match_ts(start, end, neuro, cols)

In [81]:
## 

data.shape

(170, 5, 8)

In [7]:
np.save('sample.npy',data)

In [8]:
np.load('sample.npy').shape

(170, 5, 8)

In [86]:
y.shape

(181, 3)

In [119]:
''' 중립 vs 안중립 '''

y = onehot_label(label, 'arousal')
y.shape

y_ =[]

for x in y:
    if x[0] == 1:
        y_.append(1)
        continue
    if x[1] == 1:
        y_.append(0)
        continue
    if x[2] == 1:
        y_.append(1)
        continue
         
    y_.append(-1)


/home/doomguy/projects/02_SDS_PROJ/converter.py:45: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label['l'] = label[col]<3.0
/home/doomguy/projects/02_SDS_PROJ/converter.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  label['m'] = label[col]==3.0
/home/doomguy/projects/02_SDS_PROJ/converter.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydat

In [ ]:
#smote --> knn augumentation 

In [120]:
y= np.array(y_)

In [154]:
# index of 
y_=np.where(y== 1)

In [143]:
np.random.rand(5,8)*1e-5

array([[4.74988530e-05, 6.09364872e-05, 9.06915887e-06, 2.85990846e-05,
        7.01668038e-05, 4.48259981e-05, 7.93760961e-05, 8.20737425e-05],
       [8.14579679e-05, 8.19583074e-05, 4.66922011e-05, 2.13625415e-05,
        5.43329370e-05, 4.96894399e-05, 9.69486096e-06, 1.11955483e-05],
       [7.07268136e-05, 9.88455054e-06, 2.17717203e-06, 4.01572630e-05,
        9.91986364e-05, 5.65268301e-05, 6.91606038e-05, 3.34978168e-05],
       [4.57803041e-05, 9.12499115e-05, 2.08171810e-05, 9.85180252e-05,
        4.46903934e-05, 7.99590189e-05, 9.21926939e-05, 4.33155251e-07],
       [1.69020732e-05, 7.91468875e-05, 8.82065781e-05, 2.87669196e-05,
        2.73720935e-05, 8.24260948e-05, 4.99544189e-06, 9.92443488e-05]])

In [145]:
data_ = np.array([data[i] for i in np.where(y==1)])

In [149]:
data_[0][0]

array([[4.3805540e-02, 2.2329703e-02, 1.5428959e-02, 2.2470227e-02,
        2.7197918e-03, 2.1924647e-03, 4.2104912e-01, 2.3558897e-01],
       [5.3477362e-03, 1.0489467e-02, 6.1514755e-03, 1.5976857e-02,
        7.6636299e-04, 1.3246925e-03, 3.1276476e-01, 3.8993824e-02],
       [2.2756201e-03, 1.0420798e-02, 3.1535330e-03, 2.9547713e-03,
        6.3655939e-04, 3.8912118e-04, 2.9500196e-02, 1.7355151e-02],
       [1.0652591e-02, 1.3482774e-02, 2.7158804e-02, 3.0517183e-02,
        2.2573664e-03, 1.9838517e-03, 2.8739107e-01, 1.2208119e-01],
       [8.1692273e-03, 4.2863887e-02, 1.0452670e-02, 1.9539215e-02,
        1.3803226e-03, 2.2478050e-03, 1.7229955e-01, 1.7262523e-01]],
      dtype=float32)

In [152]:
for i in range(len(data_[0])):
    data_[0][i]+=np.random.rand(5,8)*3e-5

In [153]:
data_[0][0]

array([[4.3815844e-02, 2.2359146e-02, 1.5451259e-02, 2.2496883e-02,
        2.7333498e-03, 2.2194756e-03, 4.2107868e-01, 2.3561171e-01],
       [5.3650639e-03, 1.0515835e-02, 6.1852247e-03, 1.6002335e-02,
        7.9012883e-04, 1.3504402e-03, 3.1278449e-01, 3.9002594e-02],
       [2.2924580e-03, 1.0427114e-02, 3.1580790e-03, 2.9639006e-03,
        6.5810542e-04, 4.1063814e-04, 2.9522721e-02, 1.7372925e-02],
       [1.0680028e-02, 1.3492673e-02, 2.7183156e-02, 3.0553428e-02,
        2.2865653e-03, 2.0121501e-03, 2.8742468e-01, 1.2209133e-01],
       [8.1974613e-03, 4.2871233e-02, 1.0455268e-02, 1.9558320e-02,
        1.3968180e-03, 2.2572950e-03, 1.7230254e-01, 1.7265396e-01]],
      dtype=float32)

## Normalize & Split

In [121]:
data= data.astype('float32')

In [156]:
data = np.concatenate((data, data_[0]), axis=0)
y = np.concatenate((y[:170], y_[0]), axis=0)

In [157]:
data.shape, y.shape

((196, 5, 8), (196,))

In [158]:
from sklearn.model_selection import train_test_split

#user by user 
data = (data- data.min())/(data.max() - data.min())

X_train, X_test, y_train, y_test = train_test_split(data, y, random_state=0)
X_train.shape, X_test.shape

((147, 5, 8), (49, 5, 8))

In [159]:
import tensorflow as tf

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model


In [160]:
X_train = X_train[..., tf.newaxis]
X_test = X_test[..., tf.newaxis]

In [161]:
X_train.shape

(147, 5, 8, 1)

In [162]:
train_ds = tf.data.Dataset.from_tensor_slices(
    (X_train, y_train)).shuffle(10000).batch(12)
test_ds = tf.data.Dataset.from_tensor_slices((X_test, y_test)).batch(12)

In [163]:
class MyModel(Model):
  def __init__(self):
    super(MyModel, self).__init__()
    self.conv1 = Conv2D(3, 1, activation='relu')
    self.conv2 = Conv2D(2, 3, activation='relu')
    self.conv3= Conv2D(1, 1, activation='relu')
    self.flatten = Flatten()
    self.d1 = Dense(62, activation='relu')
    self.d2 = Dense(3, activation='softmax')

  def call(self, x):
    x = self.conv1(x)
    x = self.conv2(x)
    x = self.conv3(x)
    x = self.flatten(x)
#     print(x.shape)
    x = self.d1(x)
#     print(x.shape)
    return self.d2(x)

model = MyModel()

In [164]:
loss_object = tf.keras.losses.SparseCategoricalCrossentropy()

optimizer = tf.keras.optimizers.Adam()

train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

test_loss = tf.keras.metrics.Mean(name='test_loss')
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')

@tf.function
def train_step(images, labels):
  with tf.GradientTape() as tape:
    predictions = model(images)
    loss = loss_object(labels, predictions)
  gradients = tape.gradient(loss, model.trainable_variables)
  optimizer.apply_gradients(zip(gradients, model.trainable_variables))

  train_loss(loss)
  train_accuracy(labels, predictions)
# f1 , auc, roc 
    
@tf.function
def test_step(images, labels):
  predictions = model(images)
  t_loss = loss_object(labels, predictions)

  test_loss(t_loss)
  test_accuracy(labels, predictions)

In [165]:
EPOCHS = 2000

for epoch in range(EPOCHS):
  for images, labels in train_ds:
    train_step(images, labels)

  for test_images, test_labels in test_ds:
    test_step(test_images, test_labels)

  template = '에포크: {}, 손실: {}, 정확도: {}, 테스트 손실: {}, 테스트 정확도: {}'
  if epoch % 100 == 0 :
      print (template.format(epoch+1,
                             train_loss.result(),
                             train_accuracy.result()*100,
                             test_loss.result(),
                             test_accuracy.result()*100))

에포크: 1, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 101, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 201, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 301, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 401, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 501, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 601, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 701, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 801, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 901, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 1001, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크: 1101, 손실: nan, 정확도: 72.10884094238281, 테스트 손실: nan, 테스트 정확도: 79.59183502197266
에포크:

In [166]:
list(y_train).count(1)/len(y_train)

0.14285714285714285

In [167]:
list(y_test).count(1)/len(y_test)

0.12244897959183673